/**
 * Curated mapping of ticker symbols to full company names.
 * Used by semantic search to match user queries like "apple" -> AAPL.
 */

export const COMPANY_NAMES: Record<string, { name: string; sector: string }> = {
  AAPL: { name: "Apple Inc.", sector: "Technology" },
  MSFT: { name: "Microsoft Corporation", sector: "Technology" },
  GOOGL: { name: "Alphabet Inc.", sector: "Technology" },
  GOOG: { name: "Alphabet Inc.", sector: "Technology" },
  AMZN: { name: "Amazon.com Inc.", sector: "Retail" },
  NVDA: { name: "NVIDIA Corporation", sector: "Semiconductors" },
  META: { name: "Meta Platforms Inc.", sector: "Technology" },
  TSLA: { name: "Tesla Inc.", sector: "Automobiles" },
  AVGO: { name: "Broadcom Inc.", sector: "Semiconductors" },
  ORCL: { name: "Oracle Corporation", sector: "Technology" },
  CRM: { name: "Salesforce Inc.", sector: "Technology" },
  AMD: { name: "Advanced Micro Devices Inc.", sector: "Semiconductors" },
  INTC: { name: "Intel Corporation", sector: "Semiconductors" },
  CSCO: { name: "Cisco Systems Inc.", sector: "Technology" },
  ADBE: { name: "Adobe Inc.", sector: "Technology" },
  NFLX: { name: "Netflix Inc.", sector: "Media" },
  JPM: { name: "JPMorgan Chase & Co.", sector: "Banking" },
  BAC: { name: "Bank of America Corp.", sector: "Banking" },
  WFC: { name: "Wells Fargo & Co.", sector: "Banking" },
  GS: { name: "Goldman Sachs Group Inc.", sector: "Banking" },
  MS: { name: "Morgan Stanley", sector: "Banking" },
  BLK: { name: "BlackRock Inc.", sector: "Asset Management" },
  AXP: { name: "American Express Co.", sector: "Financial Services" },
  C: { name: "Citigroup Inc.", sector: "Banking" },
  V: { name: "Visa Inc.", sector: "Financial Services" },
  MA: { name: "Mastercard Incorporated", sector: "Financial Services" },
  UNH: { name: "UnitedHealth Group Inc.", sector: "Healthcare" },
  JNJ: { name: "Johnson & Johnson", sector: "Healthcare" },
  LLY: { name: "Eli Lilly and Company", sector: "Pharmaceuticals" },
  PFE: { name: "Pfizer Inc.", sector: "Pharmaceuticals" },
  ABBV: { name: "AbbVie Inc.", sector: "Pharmaceuticals" },
  MRK: { name: "Merck & Co. Inc.", sector: "Pharmaceuticals" },
  TMO: { name: "Thermo Fisher Scientific Inc.", sector: "Healthcare" },
  ABT: { name: "Abbott Laboratories", sector: "Healthcare" },
  DHR: { name: "Danaher Corporation", sector: "Healthcare" },
  WMT: { name: "Walmart Inc.", sector: "Retail" },
  PG: { name: "Procter & Gamble Co.", sector: "Consumer Staples" },
  KO: { name: "The Coca-Cola Company", sector: "Beverages" },
  PEP: { name: "PepsiCo Inc.", sector: "Beverages" },
  MCD: { name: "McDonalds Corporation", sector: "Restaurants" },
  NKE: { name: "Nike Inc.", sector: "Apparel" },
  SBUX: { name: "Starbucks Corporation", sector: "Restaurants" },
  TGT: { name: "Target Corporation", sector: "Retail" },
  COST: { name: "Costco Wholesale Corp.", sector: "Retail" },
  HD: { name: "Home Depot Inc.", sector: "Retail" },
  BA: { name: "Boeing Company", sector: "Aerospace" },
  CAT: { name: "Caterpillar Inc.", sector: "Machinery" },
  GE: { name: "General Electric Co.", sector: "Industrials" },
  HON: { name: "Honeywell International Inc.", sector: "Industrials" },
  UPS: { name: "United Parcel Service Inc.", sector: "Logistics" },
  RTX: { name: "RTX Corporation", sector: "Aerospace" },
  LMT: { name: "Lockheed Martin Corp.", sector: "Aerospace" },
  DE: { name: "Deere & Company", sector: "Machinery" },
  XOM: { name: "Exxon Mobil Corporation", sector: "Energy" },
  CVX: { name: "Chevron Corporation", sector: "Energy" },
  COP: { name: "ConocoPhillips", sector: "Energy" },
  SLB: { name: "Schlumberger Limited", sector: "Energy Services" },
  EOG: { name: "EOG Resources Inc.", sector: "Energy" },
  OXY: { name: "Occidental Petroleum Corp.", sector: "Energy" },
  F: { name: "Ford Motor Company", sector: "Automobiles" },
  GM: { name: "General Motors Co.", sector: "Automobiles" },
  TM: { name: "Toyota Motor Corp.", sector: "Automobiles" },
  STLA: { name: "Stellantis N.V.", sector: "Automobiles" },
  RIVN: { name: "Rivian Automotive Inc.", sector: "Automobiles" },
  T: { name: "AT&T Inc.", sector: "Telecom" },
  VZ: { name: "Verizon Communications Inc.", sector: "Telecom" },
  TMUS: { name: "T-Mobile US Inc.", sector: "Telecom" },
  CMCSA: { name: "Comcast Corporation", sector: "Telecom" },
  AMT: { name: "American Tower Corporation", sector: "Real Estate" },
  PLD: { name: "Prologis Inc.", sector: "Real Estate" },
  CCI: { name: "Crown Castle Inc.", sector: "Real Estate" },
  NEE: { name: "NextEra Energy Inc.", sector: "Utilities" },
  DUK: { name: "Duke Energy Corp.", sector: "Utilities" },
  SO: { name: "Southern Company", sector: "Utilities" },
  LIN: { name: "Linde plc", sector: "Materials" },
  APD: { name: "Air Products and Chemicals Inc.", sector: "Materials" },
  ECL: { name: "Ecolab Inc.", sector: "Materials" },
  PM: { name: "Philip Morris International Inc.", sector: "Tobacco" },
  MO: { name: "Altria Group Inc.", sector: "Tobacco" },
  CL: { name: "Colgate-Palmolive Company", sector: "Consumer Staples" },
  EL: { name: "Estee Lauder Companies Inc.", sector: "Consumer Staples" },
  MAR: { name: "Marriott International Inc.", sector: "Hotels" },
  HLT: { name: "Hilton Worldwide Holdings Inc.", sector: "Hotels" },
  BKNG: { name: "Booking Holdings Inc.", sector: "Travel" },
  COIN: { name: "Coinbase Global Inc.", sector: "Cryptocurrency Exchange" },
  MSTR: { name: "MicroStrategy Incorporated", sector: "Software" },
  PLTR: { name: "Palantir Technologies Inc.", sector: "Software" },
  SNOW: { name: "Snowflake Inc.", sector: "Software" },
  CRWD: { name: "CrowdStrike Holdings Inc.", sector: "Cybersecurity" },
  NET: { name: "Cloudflare Inc.", sector: "Software" },
  PANW: { name: "Palo Alto Networks Inc.", sector: "Cybersecurity" },
  ZS: { name: "Zscaler Inc.", sector: "Cybersecurity" },
  ABNB: { name: "Airbnb Inc.", sector: "Travel" },
  DASH: { name: "DoorDash Inc.", sector: "Food Delivery" },
  UBER: { name: "Uber Technologies Inc.", sector: "Mobility" },
  LYFT: { name: "Lyft Inc.", sector: "Mobility" },
  PYPL: { name: "PayPal Holdings Inc.", sector: "Financial Services" },
  SHOP: { name: "Shopify Inc.", sector: "Software" },
  SPOT: { name: "Spotify Technology S.A.", sector: "Media" },
  GME: { name: "GameStop Corp.", sector: "Retail" },
  AMC: { name: "AMC Entertainment Holdings Inc.", sector: "Entertainment" },
  BB: { name: "BlackBerry Limited", sector: "Software" },
  NOK: { name: "Nokia Corporation", sector: "Telecom" },
  TLRY: { name: "Tilray Brands Inc.", sector: "Pharmaceuticals" },
  ACB: { name: "Aurora Cannabis Inc.", sector: "Pharmaceuticals" },
  CGC: { name: "Canopy Growth Corporation", sector: "Pharmaceuticals" },
  FUBO: { name: "fuboTV Inc.", sector: "Media" },
  RBLX: { name: "Roblox Corporation", sector: "Gaming" },
  DDOG: { name: "Datadog Inc.", sector: "Software" },
  MDB: { name: "MongoDB Inc.", sector: "Software" },
  TEAM: { name: "Atlassian Corporation", sector: "Software" },
  ADSK: { name: "Autodesk Inc.", sector: "Software" },
  DOCU: { name: "DocuSign Inc.", sector: "Software" },
  ZM: { name: "Zoom Video Communications Inc.", sector: "Software" },
  SPY: { name: "SPDR S&P 500 ETF Trust", sector: "ETF" },
  VOO: { name: "Vanguard S&P 500 ETF", sector: "ETF" },
  IVV: { name: "iShares Core S&P 500 ETF", sector: "ETF" },
  VTI: { name: "Vanguard Total Stock Market ETF", sector: "ETF" },
  QQQ: { name: "Invesco QQQ Trust", sector: "ETF" },
  VEA: { name: "Vanguard FTSE Developed Markets ETF", sector: "ETF" },
  VTV: { name: "Vanguard Value ETF", sector: "ETF" },
  IEFA: { name: "iShares Core MSCI EAFE ETF", sector: "ETF" },
  VWO: { name: "Vanguard FTSE Emerging Markets ETF", sector: "ETF" },
  IEMG: { name: "iShares Core MSCI Emerging Markets ETF", sector: "ETF" },
  IJR: { name: "iShares Core S&P Small-Cap ETF", sector: "ETF" },
  BND: { name: "Vanguard Total Bond Market ETF", sector: "ETF" },
  VUG: { name: "Vanguard Growth ETF", sector: "ETF" },
  IWF: { name: "iShares Russell 1000 Growth ETF", sector: "ETF" },
  BNDX: { name: "Vanguard Total International Bond ETF", sector: "ETF" },
  IWM: { name: "iShares Russell 2000 ETF", sector: "ETF" },
  VIG: { name: "Vanguard Dividend Appreciation ETF", sector: "ETF" },
  IJH: { name: "iShares Core S&P Mid-Cap ETF", sector: "ETF" },
  VGT: { name: "Vanguard Information Technology ETF", sector: "ETF" },
  VXUS: { name: "Vanguard Total International Stock ETF", sector: "ETF" },
  ITOT: { name: "iShares Core S&P Total US Stock Market ETF", sector: "ETF" },
  SCHB: { name: "Schwab US Broad Market ETF", sector: "ETF" },
  EFA: { name: "iShares MSCI EAFE ETF", sector: "ETF" },
  VB: { name: "Vanguard Small-Cap ETF", sector: "ETF" },
  SCHD: { name: "Schwab US Dividend Equity ETF", sector: "ETF" },
  VV: { name: "Vanguard Large-Cap ETF", sector: "ETF" },
  TLT: { name: "iShares 20+ Year Treasury Bond ETF", sector: "ETF" },
  BIV: { name: "Vanguard Intermediate-Term Bond ETF", sector: "ETF" },
  GLD: { name: "SPDR Gold Shares", sector: "Commodity ETF" },
  VO: { name: "Vanguard Mid-Cap ETF", sector: "ETF" },
  IVE: { name: "iShares S&P 500 Value ETF", sector: "ETF" },
  QUAL: { name: "iShares MSCI USA Quality Factor ETF", sector: "ETF" },
  DIA: { name: "SPDR Dow Jones Industrial Average ETF", sector: "ETF" },
  VYM: { name: "Vanguard High Dividend Yield ETF", sector: "ETF" },
  MGV: { name: "Vanguard Mega Cap Value ETF", sector: "ETF" },
  SCHF: { name: "Schwab International Equity ETF", sector: "ETF" },
  MBB: { name: "iShares MBS ETF", sector: "ETF" },
  LQD: { name: "iShares iBoxx Investment Grade Corporate Bond ETF", sector: "ETF" },
  HYG: { name: "iShares iBoxx High Yield Corporate Bond ETF", sector: "ETF" },
  EMB: { name: "iShares JPMorgan USD Emerging Markets Bond ETF", sector: "ETF" },
  TIP: { name: "iShares TIPS Bond ETF", sector: "ETF" },
  IEI: { name: "iShares 3-7 Year Treasury Bond ETF", sector: "ETF" },
  SHY: { name: "iShares 1-3 Year Treasury Bond ETF", sector: "ETF" },
  BSV: { name: "Vanguard Short-Term Bond ETF", sector: "ETF" },
  AGG: { name: "iShares Core US Aggregate Bond ETF", sector: "ETF" },
  BTC: { name: "Bitcoin", sector: "Cryptocurrency" },
  ETH: { name: "Ethereum", sector: "Cryptocurrency" },
  SOL: { name: "Solana", sector: "Cryptocurrency" },
  BNB: { name: "Binance Coin", sector: "Cryptocurrency" },
  XRP: { name: "XRP", sector: "Cryptocurrency" },
  ADA: { name: "Cardano", sector: "Cryptocurrency" },
  AVAX: { name: "Avalanche", sector: "Cryptocurrency" },
  DOGE: { name: "Dogecoin", sector: "Cryptocurrency" },
  TRX: { name: "TRON", sector: "Cryptocurrency" },
  LINK: { name: "Chainlink", sector: "Cryptocurrency" },
  DOT: { name: "Polkadot", sector: "Cryptocurrency" },
  MATIC: { name: "Polygon", sector: "Cryptocurrency" },
  SHIB: { name: "Shiba Inu", sector: "Cryptocurrency" },
  LTC: { name: "Litecoin", sector: "Cryptocurrency" },
  BCH: { name: "Bitcoin Cash", sector: "Cryptocurrency" },
  NEAR: { name: "NEAR Protocol", sector: "Cryptocurrency" },
  ATOM: { name: "Cosmos", sector: "Cryptocurrency" },
  UNI: { name: "Uniswap", sector: "Cryptocurrency" },
  XLM: { name: "Stellar", sector: "Cryptocurrency" },
  ICP: { name: "Internet Computer", sector: "Cryptocurrency" },
  APT: { name: "Aptos", sector: "Cryptocurrency" },
  FIL: { name: "Filecoin", sector: "Cryptocurrency" },
  ARB: { name: "Arbitrum", sector: "Cryptocurrency" },
  QNT: { name: "Quant", sector: "Cryptocurrency" },
  AAVE: { name: "Aave", sector: "Cryptocurrency" },
  GRT: { name: "The Graph", sector: "Cryptocurrency" },
  ALGO: { name: "Algorand", sector: "Cryptocurrency" },
  SAND: { name: "The Sandbox", sector: "Cryptocurrency" },
  AXS: { name: "Axie Infinity", sector: "Cryptocurrency" },
  MANA: { name: "Decentraland", sector: "Cryptocurrency" },
  FTM: { name: "Fantom", sector: "Cryptocurrency" },
  FLOW: { name: "Flow", sector: "Cryptocurrency" },
  EGLD: { name: "MultiversX", sector: "Cryptocurrency" },
  CHZ: { name: "Chiliz", sector: "Cryptocurrency" },
  CRV: { name: "Curve DAO", sector: "Cryptocurrency" },
  ENJ: { name: "Enjin Coin", sector: "Cryptocurrency" },
  ZEC: { name: "Zcash", sector: "Cryptocurrency" },
  BAT: { name: "Basic Attention Token", sector: "Cryptocurrency" },
  ZRX: { name: "0x", sector: "Cryptocurrency" },
  FET: { name: "Fetch.ai", sector: "Cryptocurrency" },
  RPL: { name: "Rocket Pool", sector: "Cryptocurrency" },
  LDO: { name: "Lido DAO", sector: "Cryptocurrency" },
  OP: { name: "Optimism", sector: "Cryptocurrency" },
  MNT: { name: "Mantle", sector: "Cryptocurrency" },
  RNDR: { name: "Render", sector: "Cryptocurrency" },
  TIA: { name: "Celestia", sector: "Cryptocurrency" },
  SEI: { name: "Sei", sector: "Cryptocurrency" },
  PYTH: { name: "Pyth Network", sector: "Cryptocurrency" },
};

export function getCompanyName(symbol: string): string {
  const upper = symbol.toUpperCase().replace("-USD", "");
  return COMPANY_NAMES[upper]?.name ?? symbol;
}

export function getCompanySector(symbol: string): string {
  const upper = symbol.toUpperCase().replace("-USD", "");
  return COMPANY_NAMES[upper]?.sector ?? "—";
}
