// Auto-generated from /api/assets/list?exchange=b3 on 2026-08-22
// 341 B3 stocks. Used by lib/news-tagger.ts to detect ticker mentions in article text.

export type TickerEntry = {
  symbol: string;
  name: string;
  type: 'stock';
  aliases: string[];
};

export const B3_TICKERS: TickerEntry[] = [
  { symbol: "AALR3", name: "Allianca Saude e Participacoes SA - ALLIAR", type: "stock", aliases: ["Allianca", "ALLIAR", "AALR3"] },
  { symbol: "ABCB4", name: "Banco ABC Brasil SA Conv Pfd", type: "stock", aliases: ["ABCB4", "Banco"] },
  { symbol: "ABEV3", name: "Ambev S/A", type: "stock", aliases: ["Companhia de Bebidas das Américas", "ABEV3", "AmBev", "Ambev"] },
  { symbol: "AERI3", name: "Aeris Industria e Comercio de Equipamentos para Geracao deEnergia S.A.", type: "stock", aliases: ["AERI3", "Aeris"] },
  { symbol: "AGRO3", name: "BrasilAgro Cia Brasileira de Propriedades Agricolas", type: "stock", aliases: ["BrasilAgro", "AGRO3"] },
  { symbol: "AGXY3", name: "Agrogalaxy Participacoes SA", type: "stock", aliases: ["Agrogalaxy", "AGXY3"] },
  { symbol: "AHEB3", name: "São Paulo Turismo S.A.", type: "stock", aliases: ["AHEB3"] },
  { symbol: "ALLD3", name: "Allied Tecnologia SA", type: "stock", aliases: ["Allied", "ALLD3"] },
  { symbol: "ALOS3", name: "Allos", type: "stock", aliases: ["Allos", "ALOS3"] },
  { symbol: "ALPA3", name: "Alpargatas SA", type: "stock", aliases: ["Alpargatas", "ALPA3"] },
  { symbol: "ALPA4", name: "Alpargatas SA Pfd", type: "stock", aliases: ["Alpargatas", "ALPA4"] },
  { symbol: "ALPK3", name: "Allpark Empreendimentos Participacoes e Servicos S.A.", type: "stock", aliases: ["Allpark", "ALPK3"] },
  { symbol: "ALUP3", name: "Alupar Investimento SA", type: "stock", aliases: ["Alupar", "ALUP3"] },
  { symbol: "ALUP4", name: "Alupar Investimento SA Pfd Shs", type: "stock", aliases: ["Alupar", "ALUP4"] },
  { symbol: "AMAR3", name: "Marisa Lojas S.A.", type: "stock", aliases: ["Marisa", "AMAR3"] },
  { symbol: "AMBP3", name: "Ambipar Participacoes e Empreendimentos SA", type: "stock", aliases: ["Ambipar", "AMBP3"] },
  { symbol: "AMER3", name: "Americanas SA", type: "stock", aliases: ["Americanas", "AMER3"] },
  { symbol: "AMOB3", name: "Automob Participacoes S.A", type: "stock", aliases: ["Automob", "AMOB3"] },
  { symbol: "ANIM3", name: "Anima Holding SA", type: "stock", aliases: ["ANIM3", "Anima"] },
  { symbol: "ARML3", name: "Armac Locacao Logistica e Servicos SA", type: "stock", aliases: ["Armac", "ARML3"] },
  { symbol: "ARND3", name: "Arandu Investimentos S.A", type: "stock", aliases: ["Arandu", "ARND3"] },
  { symbol: "ASAI3", name: "Assaí", type: "stock", aliases: ["Assaí Atacadista", "ASAI3", "Assaí"] },
  { symbol: "ATED3", name: "Atom Educacao e Editora S.A.", type: "stock", aliases: ["ATED3"] },
  { symbol: "AUAU3", name: "Uniao Pet Participacoes SA", type: "stock", aliases: ["AUAU3", "Uniao"] },
  { symbol: "AURA33", name: "Aura Minerals Inc Shs Unsponsored Brazilian Depositary Receipt Repr 1 Sh", type: "stock", aliases: ["AURA33"] },
  { symbol: "AURE3", name: "Auren Energia", type: "stock", aliases: ["AURE3", "Auren"] },
  { symbol: "AXIA3", name: "Axia Energia", type: "stock", aliases: ["AXIA3"] },
  { symbol: "AXIA7", name: "AXIA Energia SA Non-Cum Perp Pfd Registered Shs C", type: "stock", aliases: ["AXIA7"] },
  { symbol: "AZEV3", name: "Azevedo & Travassos SA", type: "stock", aliases: ["Azevedo", "AZEV3"] },
  { symbol: "AZEV4", name: "Azevedo & Travassos SA Pfd", type: "stock", aliases: ["Azevedo", "AZEV4"] },
  { symbol: "AZTE3", name: "Azevedo & Travassos Energia S.A", type: "stock", aliases: ["Azevedo", "AZTE3"] },
  { symbol: "AZUL3", name: "Azul S.A.", type: "stock", aliases: ["AZUL3"] },
  { symbol: "AZUL97", name: "Azul S.A.", type: "stock", aliases: ["AZUL97"] },
  { symbol: "AZUL98", name: "Azul S.A.", type: "stock", aliases: ["AZUL98"] },
  { symbol: "AZZA3", name: "Azzas 2154", type: "stock", aliases: ["AZZA3", "Azzas"] },
  { symbol: "BAZA3", name: "Banco da Amazonia S.A.", type: "stock", aliases: ["Banco", "BAZA3"] },
  { symbol: "BBAS3", name: "Banco do Brasil", type: "stock", aliases: ["Banco do Brasil", "Banco", "BBAS3"] },
  { symbol: "BBDC3", name: "Bradesco ON", type: "stock", aliases: ["Bradesco", "BBDC3"] },
  { symbol: "BBDC4", name: "Bradesco PN", type: "stock", aliases: ["Bradespar", "Bradesco", "BBDC4"] },
  { symbol: "BBSE3", name: "BB Seguridade", type: "stock", aliases: ["BB Seguridade", "BBSE3"] },
  { symbol: "BDLL3", name: "Bardella SA Industrias Mecanicas", type: "stock", aliases: ["Bardella", "BDLL3"] },
  { symbol: "BEEF3", name: "Minerva", type: "stock", aliases: ["Minerva Foods", "Minerva", "BEEF3"] },
  { symbol: "BEES3", name: "Banestes S.A. - Banco do Estado do Espirito Santo", type: "stock", aliases: ["Banestes", "BEES3"] },
  { symbol: "BEES4", name: "Banestes SA Banco do Estado do Espirito Santo Pfd", type: "stock", aliases: ["Banestes", "BEES4"] },
  { symbol: "BGIP3", name: "Banco do Estado de Sergipe SA - Banese", type: "stock", aliases: ["Banese", "Banco", "BGIP3"] },
  { symbol: "BGIP4", name: "Banco do Estado de Sergipe SA - Banese Non-Cum Perp Pfd Registered Shs", type: "stock", aliases: ["Banco", "BGIP4"] },
  { symbol: "BHIA3", name: "Grupo Casas Bahia S.A.", type: "stock", aliases: ["Casas Bahia", "Via Varejo", "BHIA3", "Grupo"] },
  { symbol: "BIED3", name: "Bioma Educacao SA", type: "stock", aliases: ["BIED3", "Bioma"] },
  { symbol: "BIOM3", name: "Biomm SA", type: "stock", aliases: ["BIOM3", "Biomm"] },
  { symbol: "BLAU3", name: "Blau Farmaceutica SA", type: "stock", aliases: ["BLAU3"] },
  { symbol: "BMEB3", name: "BCO Mercantil do Brasil SA", type: "stock", aliases: ["BMEB3"] },
  { symbol: "BMEB4", name: "BCO Mercantil do Brasil SA Non-Cum Perp Pfd Registered Shs", type: "stock", aliases: ["BMEB4"] },
  { symbol: "BMGB4", name: "Banco Bmg SA BMG Pfd Registered Shs -144A- Reg S", type: "stock", aliases: ["Banco", "BMGB4"] },
  { symbol: "BMKS3", name: "Bicicletas Monark S.A.", type: "stock", aliases: ["Bicicletas", "BMKS3"] },
  { symbol: "BMOB3", name: "Bemobi Mobile Tech SA", type: "stock", aliases: ["Bemobi", "BMOB3"] },
  { symbol: "BNBR3", name: "Banco do Nordeste do Brasil S.A.", type: "stock", aliases: ["Banco", "BNBR3"] },
  { symbol: "BOBR4", name: "Bombril S.A.Non-Cum Perp Pfd Registered Shs", type: "stock", aliases: ["Bombril", "BOBR4"] },
  { symbol: "BPAC11", name: "BTG Pactual", type: "stock", aliases: ["BTG Pactual", "BPAC11", "BTG"] },
  { symbol: "BPAC3", name: "Banco BTG Pactual SA", type: "stock", aliases: ["Banco", "BPAC3"] },
  { symbol: "BPAC5", name: "Banco BTG Pactual SA Pfd A", type: "stock", aliases: ["Banco", "BPAC5"] },
  { symbol: "BRAP3", name: "Bradespar S.A.", type: "stock", aliases: ["Bradespar", "BRAP3"] },
  { symbol: "BRAP4", name: "Bradespar", type: "stock", aliases: ["Bradespar", "BRAP4"] },
  { symbol: "BRAV3", name: "Brava", type: "stock", aliases: ["BRAV3", "Brava"] },
  { symbol: "BRKM3", name: "Braskem S.A.", type: "stock", aliases: ["Braskem", "BRKM3"] },
  { symbol: "BRKM5", name: "Braskem", type: "stock", aliases: ["Braskem", "BRKM5"] },
  { symbol: "BRSR3", name: "Banco do Estado do Rio Grande do Sul SA", type: "stock", aliases: ["Banco", "BRSR3"] },
  { symbol: "BRSR6", name: "Banco do Estado do Rio Grande do Sul SA Pfd Series B", type: "stock", aliases: ["Banco", "BRSR6"] },
  { symbol: "BRST3", name: "Brisanet Servicos de Telecomunicacoes S.A.", type: "stock", aliases: ["Brisanet", "BRST3"] },
  { symbol: "BSLI3", name: "BRB Banco de Brasilia SA", type: "stock", aliases: ["BSLI3"] },
  { symbol: "BSLI4", name: "BRB Banco de Brasilia SA Pfd", type: "stock", aliases: ["BSLI4"] },
  { symbol: "CAMB3", name: "Cambuci SA", type: "stock", aliases: ["Cambuci", "CAMB3"] },
  { symbol: "CAML3", name: "Camil Alimentos SA", type: "stock", aliases: ["Camil", "CAML3"] },
  { symbol: "CASH3", name: "Meliuz SA", type: "stock", aliases: ["Meliuz", "CASH3"] },
  { symbol: "CBAV3", name: "Companhia Brasileira de Aluminio", type: "stock", aliases: ["Companhia", "CBAV3"] },
  { symbol: "CEAB3", name: "C&A Modas", type: "stock", aliases: ["CEAB3", "C&A"] },
  { symbol: "CEBR3", name: "Companhia Energetica de Brasilia - CEB", type: "stock", aliases: ["Companhia", "CEBR3"] },
  { symbol: "CEBR5", name: "Companhia Energetica de Brasilia - CEB Pfd A", type: "stock", aliases: ["CEB Pfd A", "Companhia", "CEBR5"] },
  { symbol: "CEBR6", name: "Companhia Energetica de Brasilia - CEB Pfd B", type: "stock", aliases: ["CEB Pfd B", "Companhia", "CEBR6"] },
  { symbol: "CEDO4", name: "Cia. de Fiacao e Tecidos Cedro e Cachoeira Pfd", type: "stock", aliases: ["CEDO4"] },
  { symbol: "CGAS3", name: "Companhia de Gas de Sao Paulo - COMGAS", type: "stock", aliases: ["Companhia", "COMGAS", "CGAS3"] },
  { symbol: "CGAS5", name: "Companhia de Gas de Sao Paulo - COMGAS Pfd Registered A", type: "stock", aliases: ["COMGAS Pfd Registered A", "Companhia", "CGAS5"] },
  { symbol: "CGRA3", name: "Grazziotin S.A.", type: "stock", aliases: ["Grazziotin", "CGRA3"] },
  { symbol: "CGRA4", name: "Grazziotin S.A. Pfd", type: "stock", aliases: ["Grazziotin", "CGRA4"] },
  { symbol: "CLSC3", name: "Centrais Eletricas de Santa Catarina S.A.", type: "stock", aliases: ["Centrais", "CLSC3"] },
  { symbol: "CLSC4", name: "Centrais Eletricas de Santa Catarina SA Pfd", type: "stock", aliases: ["Centrais", "CLSC4"] },
  { symbol: "CMIG3", name: "Companhia Energetica de Minas Gerais SA", type: "stock", aliases: ["Companhia", "CMIG3"] },
  { symbol: "CMIG4", name: "Cemig", type: "stock", aliases: ["Companhia Energética de Minas Gerais", "Cemig", "CMIG4"] },
  { symbol: "CMIN3", name: "CSN Mineração", type: "stock", aliases: ["CSN Mineração", "CMIN3"] },
  { symbol: "COCE3", name: "Companhia Energetica do Ceara-COELCE", type: "stock", aliases: ["Companhia", "COCE3"] },
  { symbol: "COCE5", name: "Companhia Energetica do Ceara-COELCE Pfd A", type: "stock", aliases: ["Companhia", "COCE5"] },
  { symbol: "COGN3", name: "Cogna Educação", type: "stock", aliases: ["COGN3", "Cogna"] },
  { symbol: "CPFE3", name: "CPFL Energia", type: "stock", aliases: ["CPFL Energia", "CPFE3", "CPFL"] },
  { symbol: "CPLE3", name: "Copel", type: "stock", aliases: ["Copel Distribuição", "Copel", "CPLE3"] },
  { symbol: "CRPG5", name: "Tronox Pigmentos do Brasil SA Pfd Registered Shs A", type: "stock", aliases: ["Tronox", "CRPG5"] },
  { symbol: "CSAN3", name: "Cosan", type: "stock", aliases: ["Cosan Logística", "Cosan", "CSAN3"] },
  { symbol: "CSED3", name: "Cruzeiro do Sul Educacional SA", type: "stock", aliases: ["Cruzeiro", "CSED3"] },
  { symbol: "CSMG3", name: "Copasa", type: "stock", aliases: ["Copasa", "CSMG3"] },
  { symbol: "CSNA3", name: "Siderúrgica Nacional", type: "stock", aliases: ["Companhia Siderúrgica Nacional", "Siderúrgica", "CSNA3", "CSN"] },
  { symbol: "CSUD3", name: "CSU Digital SA", type: "stock", aliases: ["CSUD3"] },
  { symbol: "CTKA4", name: "Karsten S.A.Non-Cum Perp Pfd Registered Shs", type: "stock", aliases: ["Karsten", "CTKA4"] },
  { symbol: "CURY3", name: "Cury", type: "stock", aliases: ["CURY3"] },
  { symbol: "CVCB3", name: "CVC Brasil Operadora e Agencia de Viagens SA", type: "stock", aliases: ["CVC Brasil", "CVCB3", "CVC"] },
  { symbol: "CXSE3", name: "Caixa Seguridade", type: "stock", aliases: ["Caixa", "CXSE3"] },
  { symbol: "CYRE3", name: "Cyrela Realty", type: "stock", aliases: ["Cyrela Brazil Realty", "Cyrela", "CYRE3"] },
  { symbol: "CYRE4", name: "Cyrela Brazil Realty SA Empreendimentos e Participacoes Pfd shs", type: "stock", aliases: ["Cyrela", "CYRE4"] },
  { symbol: "DASA3", name: "Diagnosticos da America S.A.", type: "stock", aliases: ["Diagnosticos", "DASA3"] },
  { symbol: "DESK3", name: "Desktop SA", type: "stock", aliases: ["Desktop", "DESK3"] },
  { symbol: "DEXP3", name: "Dexxos Participacoes SA", type: "stock", aliases: ["Dexxos", "DEXP3"] },
  { symbol: "DEXP4", name: "Dexxos Participacoes SA Pref", type: "stock", aliases: ["Dexxos", "DEXP4"] },
  { symbol: "DIRR3", name: "Direcional", type: "stock", aliases: ["Direcional", "DIRR3"] },
  { symbol: "DMVF3", name: "D1000 Varejo Farma Participacoes SA", type: "stock", aliases: ["D1000", "DMVF3"] },
  { symbol: "DOTZ3", name: "Dotz SA", type: "stock", aliases: ["DOTZ3"] },
  { symbol: "DXCO3", name: "Dexco SA", type: "stock", aliases: ["Dexco", "DXCO3"] },
  { symbol: "EALT3", name: "Electro Aco Altona SA", type: "stock", aliases: ["Electro", "EALT3"] },
  { symbol: "EALT4", name: "Electro Aco Altona SA Pfd", type: "stock", aliases: ["Electro", "EALT4"] },
  { symbol: "ECOM3", name: "Economatica SA", type: "stock", aliases: ["Economatica", "ECOM3"] },
  { symbol: "ECOR3", name: "EcoRodovias Infraestrutura e Logistica S.A.", type: "stock", aliases: ["EcoRodovias", "ECOR3"] },
  { symbol: "EGIE3", name: "Engie Brasil", type: "stock", aliases: ["Engie Brasil", "EGIE3", "Engie"] },
  { symbol: "EKTR4", name: "Elektro Redes S.A. Pfd Shs", type: "stock", aliases: ["Elektro", "EKTR4"] },
  { symbol: "EMAE4", name: "EMAE-Empresa Metropolitana de Aguas e Energia SA Pfd Registered", type: "stock", aliases: ["EMAE-Empresa", "EMAE4"] },
  { symbol: "EMBJ3", name: "Embraer", type: "stock", aliases: ["Embraer", "EMBJ3"] },
  { symbol: "ENEV3", name: "Eneva", type: "stock", aliases: ["Eneva Energia", "ENEV3", "Eneva"] },
  { symbol: "ENGI11", name: "Energisa", type: "stock", aliases: ["Energisa", "ENGI11"] },
  { symbol: "ENGI3", name: "Energisa SA", type: "stock", aliases: ["Energisa", "ENGI3"] },
  { symbol: "ENGI4", name: "Energisa SA Pfd Shs Non-Voting", type: "stock", aliases: ["Energisa", "ENGI4"] },
  { symbol: "ENJU3", name: "Enjoei SA", type: "stock", aliases: ["Enjoei", "ENJU3"] },
  { symbol: "ENMT3", name: "Energisa Mato Grosso - Distribuidora de Energia Sa", type: "stock", aliases: ["Distribuidora de Energia", "Energisa", "ENMT3"] },
  { symbol: "ENMT4", name: "Energisa Mato Grosso - Distribuidora de Energia Sa Pfd Shs", type: "stock", aliases: ["Energisa", "ENMT4"] },
  { symbol: "EPAR3", name: "Embpar Participacoes SA", type: "stock", aliases: ["Embpar", "EPAR3"] },
  { symbol: "EQPA3", name: "Equatorial Para Distribuidora de Energia SA", type: "stock", aliases: ["Equatorial", "EQPA3"] },
  { symbol: "EQTL3", name: "Equatorial", type: "stock", aliases: ["Equatorial Energia", "Equatorial", "EQTL3"] },
  { symbol: "ESPA3", name: "MPM Corporeos SA", type: "stock", aliases: ["ESPA3"] },
  { symbol: "ETER3", name: "Eternit S.A.", type: "stock", aliases: ["Eternit", "ETER3"] },
  { symbol: "EUCA3", name: "Eucatex S.A. Industria e Comercio", type: "stock", aliases: ["Eucatex", "EUCA3"] },
  { symbol: "EUCA4", name: "Eucatex S.A. Industria E Comercio Non-Cum Perp Pfd Registered Shs", type: "stock", aliases: ["Eucatex", "EUCA4"] },
  { symbol: "EVEB31", name: "Eve Holding Inc Unsponsored BDR Repr 1 Sh", type: "stock", aliases: ["EVEB31"] },
  { symbol: "EVEN3", name: "Even Construtora E Incorporadora S.A.", type: "stock", aliases: ["EVEN3"] },
  { symbol: "EVTC31", name: "EVERTEC, Inc. Shs Sponsored Brazilian Depositary Receipt Repr 1 Sh", type: "stock", aliases: ["EVERTEC", "EVTC31"] },
  { symbol: "EZTC3", name: "EZ TEC Empreendimentos e Participacoes SA", type: "stock", aliases: ["EZTC3"] },
  { symbol: "FESA3", name: "Cia de Ferro Ligas da Bahia", type: "stock", aliases: ["FESA3"] },
  { symbol: "FESA4", name: "Cia de Ferro Ligas da Bahia-Ferbasa Pfd", type: "stock", aliases: ["FESA4"] },
  { symbol: "FHER3", name: "Fertilizantes Heringer S.A.", type: "stock", aliases: ["Fertilizantes", "FHER3"] },
  { symbol: "FICT3", name: "Fictor Alimentos SA", type: "stock", aliases: ["Fictor", "FICT3"] },
  { symbol: "FIQE3", name: "Unifique Telecomunicacoes SA", type: "stock", aliases: ["Unifique", "FIQE3"] },
  { symbol: "FLRY3", name: "Fleury", type: "stock", aliases: ["Fleury Medicina", "Fleury", "FLRY3"] },
  { symbol: "FRAS3", name: "Fras-Le S.A.", type: "stock", aliases: ["Fras-Le", "FRAS3"] },
  { symbol: "GEPA4", name: "Rio Paranapanema Energia SA Pfd Registered", type: "stock", aliases: ["GEPA4"] },
  { symbol: "GFSA3", name: "Gafisa S.A.", type: "stock", aliases: ["Gafisa", "GFSA3"] },
  { symbol: "GGBR3", name: "Gerdau S.A.", type: "stock", aliases: ["Gerdau", "GGBR3"] },
  { symbol: "GGBR4", name: "Gerdau", type: "stock", aliases: ["Gerdau Metalúrgica", "Gerdau", "GGBR4"] },
  { symbol: "GGPS3", name: "GPS Participacoes e Empreendimentos SA", type: "stock", aliases: ["GGPS3"] },
  { symbol: "GMAT3", name: "Grupo Mateus SA", type: "stock", aliases: ["GMAT3", "Grupo"] },
  { symbol: "GOAU3", name: "Metalurgica Gerdau S.A.", type: "stock", aliases: ["Metalurgica", "GOAU3"] },
  { symbol: "GOAU4", name: "Gerdau Met", type: "stock", aliases: ["Gerdau", "GOAU4"] },
  { symbol: "GRND3", name: "Grendene S.A.", type: "stock", aliases: ["Grendene", "GRND3"] },
  { symbol: "HAGA4", name: "Haga SA Industria e Comercio Pfd", type: "stock", aliases: ["HAGA4"] },
  { symbol: "HAPV3", name: "Hapvida", type: "stock", aliases: ["Hapvida Assistência Médica", "Hapvida", "HAPV3"] },
  { symbol: "HBOR3", name: "Helbor Empreendimentos S.A.", type: "stock", aliases: ["Helbor", "HBOR3"] },
  { symbol: "HBRE3", name: "HBR Realty Empreendimentos Imobiliarios SA", type: "stock", aliases: ["HBRE3"] },
  { symbol: "HBSA3", name: "Hidrovias do Brasil SA", type: "stock", aliases: ["Hidrovias", "HBSA3"] },
  { symbol: "HBTS5", name: "Cia Habitasul de Participacoes Pfd A", type: "stock", aliases: ["HBTS5"] },
  { symbol: "HOOT4", name: "Hoteis Othon SA Pfd", type: "stock", aliases: ["Hoteis", "HOOT4"] },
  { symbol: "HYPE3", name: "Hypera", type: "stock", aliases: ["Hypera Pharma", "Hypera", "HYPE3"] },
  { symbol: "IFCM3", name: "Infracommerce CXAAS SA", type: "stock", aliases: ["Infracommerce", "IFCM3"] },
  { symbol: "IGTI11", name: "Iguatemi", type: "stock", aliases: ["Iguatemi", "IGTI11"] },
  { symbol: "IGTI3", name: "Iguatemi SA", type: "stock", aliases: ["Iguatemi", "IGTI3"] },
  { symbol: "IGTI4", name: "Iguatemi SA Perp Pfd Registered Shs", type: "stock", aliases: ["Iguatemi", "IGTI4"] },
  { symbol: "INBR32", name: "Inter & Co., Inc. Shs Unsponsored Brazilian Depositary Receipt Repr 1 Sh", type: "stock", aliases: ["INBR32", "Inter"] },
  { symbol: "INEP3", name: "Inepar SA Industria e Construcoes", type: "stock", aliases: ["Inepar", "INEP3"] },
  { symbol: "INEP4", name: "Inepar SA Industria e Construcoes Pfd", type: "stock", aliases: ["Inepar", "INEP4"] },
  { symbol: "INTB3", name: "Intelbras SA Industria de Telecomunicacao Eletronica Brasileir", type: "stock", aliases: ["Intelbras", "INTB3"] },
  { symbol: "IRBR3", name: "IRB Brasil Resseguros SA", type: "stock", aliases: ["IRBR3"] },
  { symbol: "ISAE3", name: "Isa Energia Brasil SA", type: "stock", aliases: ["ISAE3"] },
  { symbol: "ISAE4", name: "ISA Energia", type: "stock", aliases: ["ISAE4"] },
  { symbol: "ITSA3", name: "Itausa SA", type: "stock", aliases: ["Itausa", "ITSA3"] },
  { symbol: "ITSA4", name: "Itausa", type: "stock", aliases: ["Itausa", "Itaúsa", "ITSA4"] },
  { symbol: "ITUB3", name: "Itau Unibanco Holding S.A.", type: "stock", aliases: ["ITUB3"] },
  { symbol: "ITUB4", name: "Itaú Unibanco", type: "stock", aliases: ["Itaú Unibanco", "ITUB4", "Itau", "Itaú"] },
  { symbol: "JALL3", name: "Jalles Machado SA", type: "stock", aliases: ["Jalles", "JALL3"] },
  { symbol: "JBSS32", name: "JBS N.V. Shs Sponsored Brazilian Depositary Receipt Repr 1 Sh A", type: "stock", aliases: ["JBSS32"] },
  { symbol: "JFEN3", name: "Joao Fortes Engenharia S.A.", type: "stock", aliases: ["JFEN3"] },
  { symbol: "JHSF3", name: "JHSF Participacoes S.A.", type: "stock", aliases: ["JHSF3"] },
  { symbol: "JSLG3", name: "JSL S.A.", type: "stock", aliases: ["JSLG3"] },
  { symbol: "KEPL3", name: "Kepler Weber SA", type: "stock", aliases: ["Kepler", "KEPL3"] },
  { symbol: "KLBN11", name: "Klabin", type: "stock", aliases: ["Klabin", "KLBN11"] },
  { symbol: "KLBN3", name: "Klabin SA", type: "stock", aliases: ["Klabin", "KLBN3"] },
  { symbol: "KLBN4", name: "Klabin SA Non-Cum Perp Pfd Registered Shs", type: "stock", aliases: ["Klabin", "KLBN4"] },
  { symbol: "LAND3", name: "Terra Santa Propriedades Agricolas SA", type: "stock", aliases: ["LAND3", "Terra"] },
  { symbol: "LAVV3", name: "LAVVI Empreendimentos Imobiliarios SA", type: "stock", aliases: ["LAVV3", "LAVVI"] },
  { symbol: "LEVE3", name: "Mahle-Metal Leve S.A.", type: "stock", aliases: ["Mahle-Metal", "LEVE3"] },
  { symbol: "LIGT3", name: "Light S.A.", type: "stock", aliases: ["Light", "LIGT3"] },
  { symbol: "LJQQ3", name: "Lojas Quero-Quero SA", type: "stock", aliases: ["LJQQ3", "Lojas"] },
  { symbol: "LOGG3", name: "Log Commercial Properties e Participacoes SA", type: "stock", aliases: ["LOGG3"] },
  { symbol: "LOGN3", name: "Log-In Logistica Intermodal SA", type: "stock", aliases: ["Log-In", "LOGN3"] },
  { symbol: "LPSB3", name: "LPS Brasil-Consultoria de Imoveis SA", type: "stock", aliases: ["LPSB3"] },
  { symbol: "LREN3", name: "Lojas Renner", type: "stock", aliases: ["Lojas Renner", "Renner", "Lojas", "LREN3"] },
  { symbol: "LUPA3", name: "Lupatech S.A.", type: "stock", aliases: ["Lupatech", "LUPA3"] },
  { symbol: "LUXM4", name: "Trevisa Investimentos SA Pfd", type: "stock", aliases: ["Trevisa", "LUXM4"] },
  { symbol: "LWSA3", name: "LWSA S.A.", type: "stock", aliases: ["Locaweb Serviços", "Locaweb", "LWSA3"] },
  { symbol: "MATD3", name: "Hospital Mater Dei SA", type: "stock", aliases: ["Hospital", "MATD3"] },
  { symbol: "MBRF3", name: "Marfrig", type: "stock", aliases: ["Marfrig", "MBRF3"] },
  { symbol: "MDIA3", name: "M. Dias Branco SA Industria e Comercio de Alimentos", type: "stock", aliases: ["MDIA3"] },
  { symbol: "MDNE3", name: "Moura Dubeux Engenharia SA", type: "stock", aliases: ["MDNE3", "Moura"] },
  { symbol: "MEAL3", name: "International Meal Company Alimentacao SA", type: "stock", aliases: ["International", "MEAL3"] },
  { symbol: "MELK3", name: "Melnick Desenvolvimento Imobiliario SA", type: "stock", aliases: ["Melnick", "MELK3"] },
  { symbol: "MGEL4", name: "Mangels Industrial SA Pfd Shs", type: "stock", aliases: ["Mangels", "MGEL4"] },
  { symbol: "MGLU3", name: "Magazine Luiza", type: "stock", aliases: ["Magazine Luiza", "Magazine", "Magalu", "MGLU3"] },
  { symbol: "MILS3", name: "Mills Locacao Servicos e Logistica S.A.", type: "stock", aliases: ["Mills", "MILS3"] },
  { symbol: "MLAS3", name: "Multi Group S.A", type: "stock", aliases: ["MLAS3", "Multi"] },
  { symbol: "MNPR3", name: "Minupar Participacoes S.A.", type: "stock", aliases: ["Minupar", "MNPR3"] },
  { symbol: "MOTV3", name: "Motiva", type: "stock", aliases: ["Motiva", "MOTV3"] },
  { symbol: "MOVI3", name: "Movida Participacoes SA", type: "stock", aliases: ["Movida", "MOVI3"] },
  { symbol: "MRVE3", name: "MRV", type: "stock", aliases: ["MRVE3"] },
  { symbol: "MTRE3", name: "Mitre Realty Empreendimentos e Participacoes SA", type: "stock", aliases: ["Mitre", "MTRE3"] },
  { symbol: "MTSA4", name: "Metisa Metalurgica Timboense SA Pfd", type: "stock", aliases: ["Metisa", "MTSA4"] },
  { symbol: "MULT3", name: "Multiplan", type: "stock", aliases: ["Multiplan Empreendimentos", "Multiplan", "MULT3"] },
  { symbol: "MWET4", name: "Wetzel S.A. Non-Cum Perp Pfd Registered Shs", type: "stock", aliases: ["Wetzel", "MWET4"] },
  { symbol: "MYPK3", name: "Iochpe Maxion S.A.", type: "stock", aliases: ["Iochpe", "MYPK3"] },
  { symbol: "NATU3", name: "Natura", type: "stock", aliases: ["Natura", "NATU3"] },
  { symbol: "NEXP3", name: "Nexpe Participacoes SA", type: "stock", aliases: ["NEXP3", "Nexpe"] },
  { symbol: "NORD3", name: "Nordon Industrias Metalurgicas S.A.", type: "stock", aliases: ["Nordon", "NORD3"] },
  { symbol: "NUTR3", name: "Nutriplant Industria E Comercio S.A.", type: "stock", aliases: ["Nutriplant", "NUTR3"] },
  { symbol: "OBTC3", name: "Oranjebtc SA Educacao e Investimento", type: "stock", aliases: ["Oranjebtc", "OBTC3"] },
  { symbol: "OFSA3", name: "Ourofino S.A.", type: "stock", aliases: ["Ourofino", "OFSA3"] },
  { symbol: "OIBR3", name: "Oi S.A.", type: "stock", aliases: ["OIBR3"] },
  { symbol: "OIBR4", name: "Oi S.A.Non-Cum Perp Pfd Registered Shs", type: "stock", aliases: ["OIBR4"] },
  { symbol: "ONCO3", name: "Oncoclinicas do Brasil Servicos Medicos SA", type: "stock", aliases: ["Oncoclinicas", "ONCO3"] },
  { symbol: "OPCT3", name: "OceanPact Servicos Maritimos SA", type: "stock", aliases: ["OceanPact", "OPCT3"] },
  { symbol: "ORVR3", name: "Orizon Valorizacao de Residuos SA", type: "stock", aliases: ["Orizon", "ORVR3"] },
  { symbol: "OSXB3", name: "OSX Brasil S.A.", type: "stock", aliases: ["OSXB3"] },
  { symbol: "PASS3", name: "Compass Gas e Energia SA", type: "stock", aliases: ["Compass", "PASS3"] },
  { symbol: "PCAR3", name: "Companhia Brasileira de Distribuicao", type: "stock", aliases: ["Companhia", "PCAR3"] },
  { symbol: "PDGR3", name: "PDG Realty SA Empreendimentos e Participacoes", type: "stock", aliases: ["PDGR3"] },
  { symbol: "PDTC3", name: "Padtec Holding SA", type: "stock", aliases: ["Padtec", "PDTC3"] },
  { symbol: "PETR3", name: "Petrobras ON", type: "stock", aliases: ["Petrobras", "PETR3", "Petro"] },
  { symbol: "PETR4", name: "Petrobras PN", type: "stock", aliases: ["Petrobras", "PETR4", "Petro"] },
  { symbol: "PFRM3", name: "Profarma Distribuidora de Produtos Farmaceuticos SA", type: "stock", aliases: ["Profarma", "PFRM3"] },
  { symbol: "PGMN3", name: "Empreendimentos Pague Menos SA", type: "stock", aliases: ["Empreendimentos", "PGMN3"] },
  { symbol: "PINE3", name: "Banco PINE S.A.", type: "stock", aliases: ["Banco", "PINE3"] },
  { symbol: "PINE4", name: "Banco PINE S.A. Pfd", type: "stock", aliases: ["Banco", "PINE4"] },
  { symbol: "PLAS3", name: "Plascar Participacoes Industriais S.A.", type: "stock", aliases: ["Plascar", "PLAS3"] },
  { symbol: "PLPL3", name: "Plano & Plano Desenvolvimento Imobiliario Ltda", type: "stock", aliases: ["Plano", "PLPL3"] },
  { symbol: "PMAM3", name: "Paranapanema S.A.", type: "stock", aliases: ["Paranapanema", "PMAM3"] },
  { symbol: "PNVL3", name: "Dimed S.A. Distribuidora de Medicamentos", type: "stock", aliases: ["Dimed", "PNVL3"] },
  { symbol: "POMO3", name: "Marcopolo SA", type: "stock", aliases: ["Marcopolo", "POMO3"] },
  { symbol: "POMO4", name: "Marcopolo", type: "stock", aliases: ["Pomifrutas S/A", "Pomifrutas", "Marcopolo", "POMO4"] },
  { symbol: "POSI3", name: "Positivo Tecnologia SA", type: "stock", aliases: ["Positivo Tecnologia", "Positivo", "POSI3"] },
  { symbol: "PRIO3", name: "PRIO", type: "stock", aliases: ["Petro Rio", "PetroRio", "PRIO3"] },
  { symbol: "PRNR3", name: "Priner Servicos Industriais SA", type: "stock", aliases: ["Priner", "PRNR3"] },
  { symbol: "PRXB31", name: "Prosus N.V. ADR Sponsored Brazilian Depositary Receipt Repr 0.5 ADR", type: "stock", aliases: ["Prosus", "PRXB31"] },
  { symbol: "PSSA3", name: "Porto Seguro", type: "stock", aliases: ["Porto Seguro", "Porto", "PSSA3"] },
  { symbol: "PTBL3", name: "PBG S.A.Registered Shs", type: "stock", aliases: ["PTBL3"] },
  { symbol: "QUAL3", name: "Qualicorp Consultoria e Corretora de Seguros S.A.", type: "stock", aliases: ["Qualicorp", "QUAL3"] },
  { symbol: "RADL3", name: "Raia Drogasil", type: "stock", aliases: ["Raia Drogasil", "RaiaDrogasil", "RADL3"] },
  { symbol: "RAIL3", name: "Rumo", type: "stock", aliases: ["Rumo S.A", "RAIL3", "Rumo"] },
  { symbol: "RAIZ4", name: "Raizen SA Non-Cum Perp Pfd Registered Shs", type: "stock", aliases: ["Raizen", "RAIZ4"] },
  { symbol: "RANI3", name: "Irani Papel e Embalagem SA", type: "stock", aliases: ["Irani", "RANI3"] },
  { symbol: "RAPT3", name: "Randoncorp S.A.", type: "stock", aliases: ["Randoncorp", "RAPT3"] },
  { symbol: "RAPT4", name: "Randoncorp S.A.", type: "stock", aliases: ["Randoncorp", "RAPT4"] },
  { symbol: "RCSL3", name: "Recrusul SA", type: "stock", aliases: ["Recrusul", "RCSL3"] },
  { symbol: "RCSL4", name: "Recrusul SA Pfd", type: "stock", aliases: ["Recrusul", "RCSL4"] },
  { symbol: "RDOR3", name: "Rede D'Or", type: "stock", aliases: ["Rede D'Or", "RDOR3", "D'Or"] },
  { symbol: "RECV3", name: "PetroReconcavo", type: "stock", aliases: ["PetroReconcavo", "RECV3"] },
  { symbol: "REDE3", name: "Rede Energia S.A.", type: "stock", aliases: ["REDE3"] },
  { symbol: "RENT3", name: "Localiza", type: "stock", aliases: ["Localiza Rent a Car", "Localiza", "RENT3"] },
  { symbol: "RENT4", name: "Localiza Rent A Car SA Non-Cum Perp Pfd Registered Shs", type: "stock", aliases: ["Localiza", "RENT4"] },
  { symbol: "RIAA3", name: "RIACHUELO", type: "stock", aliases: ["RIACHUELO", "RIAA3"] },
  { symbol: "RNEW3", name: "Renova Energia S.A.", type: "stock", aliases: ["Renova", "RNEW3"] },
  { symbol: "RNEW4", name: "Renova Energia S.A. Pfd", type: "stock", aliases: ["Renova", "RNEW4"] },
  { symbol: "ROMI3", name: "Romi SA", type: "stock", aliases: ["ROMI3"] },
  { symbol: "RPMG3", name: "Refinaria de Petroleos Manguinhos S.A.", type: "stock", aliases: ["Refinaria", "RPMG3"] },
  { symbol: "RSUL4", name: "Metalurgica Riosulense SA Pfd", type: "stock", aliases: ["Metalurgica", "RSUL4"] },
  { symbol: "SANB11", name: "Santander Brasil", type: "stock", aliases: ["Banco Santander", "Santander", "SANB11"] },
  { symbol: "SANB3", name: "Banco Santander (Brasil) S.A.", type: "stock", aliases: ["Santander", "Banco", "SANB3"] },
  { symbol: "SANB4", name: "Banco Santander (Brasil) SA Pfd", type: "stock", aliases: ["Santander", "Banco", "SANB4"] },
  { symbol: "SAPR3", name: "Companhia de Saneamento do Parana - Sanepar", type: "stock", aliases: ["Companhia", "Sanepar", "SAPR3"] },
  { symbol: "SAPR4", name: "Companhia de Saneamento do Parana - Sanepar Non-Cum Perp Pfd Registered Shs", type: "stock", aliases: ["Companhia", "SAPR4"] },
  { symbol: "SAUD3", name: "Bradsaude SA", type: "stock", aliases: ["Bradsaude", "SAUD3"] },
  { symbol: "SBFG3", name: "Grupo SBF S.A.", type: "stock", aliases: ["Grupo", "SBFG3"] },
  { symbol: "SBSP3", name: "Sabesp", type: "stock", aliases: ["Sabesp", "SABESP", "SBSP3"] },
  { symbol: "SCAR3", name: "Sao Carlos Empreendimentos e Participacoes SA", type: "stock", aliases: ["SCAR3"] },
  { symbol: "SEER3", name: "Grupo Ser Educacional SA", type: "stock", aliases: ["Grupo", "SEER3"] },
  { symbol: "SEQL3", name: "Sequoia Logistica e Transportes SA", type: "stock", aliases: ["Sequoia", "SEQL3"] },
  { symbol: "SHOW3", name: "T4F Entretenimento S.A.", type: "stock", aliases: ["SHOW3"] },
  { symbol: "SHUL4", name: "Schulz S.A.Non-Cum Perp Pfd Registered Shs", type: "stock", aliases: ["Schulz", "SHUL4"] },
  { symbol: "SIMH3", name: "Simpar SA", type: "stock", aliases: ["Simpar", "SIMH3"] },
  { symbol: "SLCE3", name: "SLC Agrícola", type: "stock", aliases: ["SLCE3"] },
  { symbol: "SMFT3", name: "Smart Fit", type: "stock", aliases: ["Smart", "SMFT3"] },
  { symbol: "SMTO3", name: "Sao Martinho S.A.", type: "stock", aliases: ["SMTO3"] },
  { symbol: "SNSY5", name: "Sansuy SA Industria de Plasticos Pfd A", type: "stock", aliases: ["Sansuy", "SNSY5"] },
  { symbol: "SOJA3", name: "Boa Safra Sementes SA", type: "stock", aliases: ["SOJA3"] },
  { symbol: "SOND5", name: "Sondotecnica Engenharia de Solos S.A. Pfd Shs A", type: "stock", aliases: ["Sondotecnica", "SOND5"] },
  { symbol: "SUZB3", name: "Suzano", type: "stock", aliases: ["Suzano Papel", "Suzano", "SUZB3"] },
  { symbol: "SYNE3", name: "Syn Prop e Tech SA", type: "stock", aliases: ["SYNE3"] },
  { symbol: "TAEE11", name: "Taesa", type: "stock", aliases: ["Taesa Transmissora", "TAEE11", "Taesa"] },
  { symbol: "TAEE3", name: "Transmissora Alianca De Energia Eletrica S.A.", type: "stock", aliases: ["Transmissora", "TAEE3"] },
  { symbol: "TAEE4", name: "Transmissora Alianca De Energia Eletrica S.A. Pfd", type: "stock", aliases: ["Transmissora", "TAEE4"] },
  { symbol: "TASA3", name: "Taurus Armas S.A.", type: "stock", aliases: ["Taurus", "TASA3"] },
  { symbol: "TASA4", name: "Taurus Armas S.A. Pfd", type: "stock", aliases: ["Taurus", "TASA4"] },
  { symbol: "TCSA3", name: "Tecnisa S.A.", type: "stock", aliases: ["Tecnisa", "TCSA3"] },
  { symbol: "TECN3", name: "Technos S.A.", type: "stock", aliases: ["Technos", "TECN3"] },
  { symbol: "TELB4", name: "Telecomunicacoes Brasileiras SA - TELEBRAS Pref.", type: "stock", aliases: ["Telecomunicacoes", "TELEBRAS Pref", "TELB4"] },
  { symbol: "TEND3", name: "Construtora Tenda SA", type: "stock", aliases: ["Construtora", "TEND3"] },
  { symbol: "TFCO4", name: "Track & Field Co SA Pfd Registered Shs", type: "stock", aliases: ["TFCO4", "Track"] },
  { symbol: "TGMA3", name: "Tegma Gestao Logistica S.A.", type: "stock", aliases: ["Tegma", "TGMA3"] },
  { symbol: "TIMS3", name: "TIM", type: "stock", aliases: ["TIM S.A", "TIMS3", "TIM"] },
  { symbol: "TOKY3", name: "Grupo Toky SA", type: "stock", aliases: ["Grupo", "TOKY3"] },
  { symbol: "TOTS3", name: "Totvs", type: "stock", aliases: ["TOTS3", "TOTVS", "Totvs"] },
  { symbol: "TPIS3", name: "TPI - Triunfo Participacoes e Investimentos SA", type: "stock", aliases: ["TPIS3"] },
  { symbol: "TRIS3", name: "Trisul S.A.", type: "stock", aliases: ["Trisul", "TRIS3"] },
  { symbol: "TRPL15", name: "FII TRPL    CI", type: "stock", aliases: ["TRPL15"] },
  { symbol: "TTEN3", name: "Tres Tentos Agroindustrial SA", type: "stock", aliases: ["TTEN3"] },
  { symbol: "TUPY3", name: "Tupy S.A.", type: "stock", aliases: ["TUPY3"] },
  { symbol: "UCAS3", name: "Unicasa Industria de Moveis S.A.", type: "stock", aliases: ["Unicasa", "UCAS3"] },
  { symbol: "UGPA3", name: "Ultrapar", type: "stock", aliases: ["Ultrapar Participações", "Ultrapar", "UGPA3"] },
  { symbol: "UNIP3", name: "Unipar Carbocloro SA", type: "stock", aliases: ["Unipar", "UNIP3"] },
  { symbol: "UNIP5", name: "Unipar Carbocloro SA Pfd Class A", type: "stock", aliases: ["Unipar", "UNIP5"] },
  { symbol: "UNIP6", name: "Unipar Carbocloro SA Pfd Class B", type: "stock", aliases: ["Unipar", "UNIP6"] },
  { symbol: "USIM3", name: "Usinas Siderurgicas de Minas Gerais SA-Usiminas", type: "stock", aliases: ["Usinas", "USIM3"] },
  { symbol: "USIM5", name: "Usiminas", type: "stock", aliases: ["Usinas Siderúrgicas", "Usiminas", "USIM5"] },
  { symbol: "VALE3", name: "Vale", type: "stock", aliases: ["Vale S.A", "VALE3", "Vale"] },
  { symbol: "VAMO3", name: "Vamos", type: "stock", aliases: ["VAMO3", "Vamos"] },
  { symbol: "VBBR3", name: "Vibra", type: "stock", aliases: ["BR Distribuidora", "Vibra Energia", "VBBR3", "Vibra"] },
  { symbol: "VITT3", name: "Vittia S.A.", type: "stock", aliases: ["Vittia", "VITT3"] },
  { symbol: "VIVA3", name: "Vivara", type: "stock", aliases: ["Vivara", "VIVA3"] },
  { symbol: "VIVR3", name: "Viver Incorporadora e Construtora S.A.", type: "stock", aliases: ["Viver", "VIVR3"] },
  { symbol: "VIVT3", name: "Telefônica Brasil", type: "stock", aliases: ["Telefônica Brasil", "Telefônica", "VIVT3", "Vivo"] },
  { symbol: "VLID3", name: "Valid Solucoes SA", type: "stock", aliases: ["Valid", "VLID3"] },
  { symbol: "VSTE3", name: "Veste S.A. Estilo", type: "stock", aliases: ["Veste", "VSTE3"] },
  { symbol: "VTRU3", name: "Vitru Educacao SA", type: "stock", aliases: ["Vitru", "VTRU3"] },
  { symbol: "VULC3", name: "Vulcabras SA", type: "stock", aliases: ["Vulcabras", "VULC3"] },
  { symbol: "VVEO3", name: "CM Hospitalar SA", type: "stock", aliases: ["VVEO3"] },
  { symbol: "WDCN3", name: "Livetech da Bahia Industria e Comercio SA", type: "stock", aliases: ["Livetech", "WDCN3"] },
  { symbol: "WEGE3", name: "WEG", type: "stock", aliases: ["WEGE3", "Weg", "WEG"] },
  { symbol: "WEST3", name: "Westwing Comercio Varejista SA", type: "stock", aliases: ["Westwing", "WEST3"] },
  { symbol: "WHRL3", name: "Whirlpool S.A.", type: "stock", aliases: ["Whirlpool", "WHRL3"] },
  { symbol: "WHRL4", name: "Whirlpool SA Pfd", type: "stock", aliases: ["Whirlpool", "WHRL4"] },
  { symbol: "WIZC3", name: "WIZ Co Participacoes e Corretagem de Seguros SA", type: "stock", aliases: ["WIZC3"] },
  { symbol: "WLMM4", name: "WLM Participacoes e Comercio de Maquinas e Veiculos SA Pfd", type: "stock", aliases: ["WLMM4"] },
  { symbol: "XPBR31", name: "XP Inc. Shs A Unsponsored Brazilian Depositary Receipt Repr 1 Sh A", type: "stock", aliases: ["XPBR31"] },
  { symbol: "YDUQ3", name: "Yduqs", type: "stock", aliases: ["YDUQ3", "Yduqs"] },
];

// Map for quick lookup by symbol
export const B3_BY_SYMBOL: Record<string, TickerEntry> = Object.fromEntries(
  B3_TICKERS.map((t) => [t.symbol, t])
);

// Map: lowercase alias → list of tickers (for news tagger)
// Built lazily on first import; do NOT mutate B3_TICKERS after this.
let _aliasIndex: Map<string, string[]> | null = null;
export function buildAliasIndex(): Map<string, string[]> {
  if (_aliasIndex) return _aliasIndex;
  _aliasIndex = new Map();
  for (const t of B3_TICKERS) {
    for (const a of t.aliases) {
      const k = a.toLowerCase();
      if (!_aliasIndex.has(k)) _aliasIndex.set(k, []);
      _aliasIndex.get(k)!.push(t.symbol);
    }
  }
  return _aliasIndex;
}