/**
 * CVM seed data — static quarterly metrics from official CVM ITR/DFP filings.
 *
 * Generated by `npm run refresh-cvm` (scripts/refresh-cvm.ts). Each JSON file
 * at lib/cvm-data/[TICKER]/[YYYY]-[Q].json contains a normalized snapshot of
 * revenue, gross profit, EBIT, net income, and balance sheet for one quarter.
 *
 * Used as a fallback when Brapi is missing a quarter (Brapi's quarterly
 * series lags CVM by ~1 quarter).
 */

import { readFile, readdir } from "node:fs/promises";
import { join } from "node:path";

export type CvmQuarterlySeed = {
  endDate: string;
  source: "ITR" | "DFP";
  totalRevenue: number | null;
  grossProfit: number | null;
  operatingIncome: number | null;
  ebit: number | null;
  netIncome: number | null;
  totalAssets: number | null;
  totalLiabilities: number | null;
  totalEquity: number | null;
};

const DATA_DIR = join(process.cwd(), "lib", "cvm-data");

/**
 * Load all available quarterly seeds for a given ticker, sorted oldest → newest.
 * Returns [] if no seed directory exists.
 */
export async function loadCvmSeeds(ticker: string): Promise<CvmQuarterlySeed[]> {
  const tickerDir = join(DATA_DIR, ticker.toUpperCase());
  let files: string[];
  try {
    files = await readdir(tickerDir);
  } catch {
    return [];
  }
  const jsonFiles = files.filter((f) => f.endsWith(".json")).sort();
  const out: CvmQuarterlySeed[] = [];
  for (const f of jsonFiles) {
    try {
      const text = await readFile(join(tickerDir, f), "utf8");
      const parsed = JSON.parse(text) as CvmQuarterlySeed;
      out.push(parsed);
    } catch {
      // skip malformed
    }
  }
  return out;
}
